export {default as Home} from './Home'
export {default as LoginSignup} from './LoginSignup'
export {default as Activate} from './Activate'
export {default as NotFound} from './NotFound'
export {default as GoogleAuthCatcher} from './GoogleAuthCatcher'
